module.exports = {
  verbose: true,
  globals: {
    'ts-jest': {
      isolatedModules: true,
    },
  },
  setupFilesAfterEnv: ['<rootDir>/jest.js'],
  roots: ['./'],
  testEnvironment: 'jsdom',
  moduleFileExtensions: ['js', 'jsx', 'ts', 'tsx'],
  moduleDirectories: ['node_modules', 'src'],
  coverageReporters: ['json', 'lcov', 'text', 'clover', 'json-summary'],
  coverageDirectory: './coverage',
  collectCoverageFrom: [
    'src/**/*.ts',
    'src/**/*.tsx',
    // exclude files from coverage
    '!src/**/index.ts',
    '!src/**/index.tsx',
    '!src/**/App.tsx',
    '!src/**/react-app-env.d.ts',
    '!src/**/reportWebVitals.ts',
    '!src/**/setupTests.ts',
    '!src/assets/**/*',
    '!src/screens/**/*',
    '!src/components/BorderGlow/**/*',
    '!src/components/Button/**/*',
    '!src/components/CardComponent/**/*',
    '!src/components/Chip/**/*',
    '!src/components/CoverText/**/*',
    '!src/components/Cursor/**/*',
    '!src/components/DotPattern/**/*',
    '!src/components/FallingText/**/*',
    '!src/components/GlassBox/**/*',
    '!src/components/LightPillar/**/*',
    '!src/components/Orb/**/*',
    '!src/components/SpotlightCard/**/*',
    '!src/components/Timeline/**/*',
    '!src/components/TitleBox/**/*',
    '!src/components/ArticleCard/**/*',
    '!src/components/Noise/**/*',
    '!src/components/animateModal/**/*',
    '!src/components/WebsiteLoader/**/*',
    '!src/components/MdPreview/utils.ts',
    '!src/components/Theme/colors.ts',
    '!src/components/Theme/fonts.ts',
    '!src/components/Theme/theme.ts',
    '!src/router/**/*',
    '!src/providers/themeProvider/**/*',
    '!src/providers/routerProvider/**/*',
    '!src/providers/fuseProvider/**/*',
    '!src/data/**/*',
    '!src/localization/**/*',
    '!src/testUtils/**/*',
  ],
  moduleNameMapper: {
    '@assets/(.*)': '<rootDir>/src/assets/$1',
    '@assets': '<rootDir>/src/assets',
    '@screens': '<rootDir>/src/screens',
    '@services': '<rootDir>/src/services',
    '@screens/(.*)': '<rootDir>/src/screens/$1',
    '@data': '<rootDir>/src/data',
    '@hooks': '<rootDir>/src/hooks',
    '@store/slice': '<rootDir>/src/store/slice',
    '@store': '<rootDir>/src/store',
    '@selectors': '<rootDir>/src/store/selectors',
    '@components': '<rootDir>/src/components',
    '@localization': '<rootDir>/src/localization',
    '@providers': '<rootDir>/src/providers',
    '@router': '<rootDir>/src/router',
    '^.+.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$':
      'jest-transform-stub',
  },
  transform: {
    '.+\\.(css|scss|png|jpg|svg)$': 'jest-transform-stub',
    '^.+\\.(js|jsx|ts|tsx)$': 'ts-jest',
  },
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
};
