/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
ExporterVersion: 2.2.0
*/

import { useAnimations, useGLTF } from '@react-three/drei';
import { forwardRef, useEffect } from 'react';

useGLTF.preload('/ReapTheWhirlwind.glb');

const Model = forwardRef((props, ref) => {
  const { scene, animations } = useGLTF('/ReapTheWhirlwind.glb');
  const { actions } = useAnimations(animations, ref);

  scene.traverse((child) => {
    if (child.isMesh) {
      child.castShadow = true;
      child.receiveShadow = true;
      child.material.metalness = 0.4;
      child.material.roughness = 0.4;
      child.material.envMapIntensity = 1;
    }
  });

  useEffect(() => {
    console.log('Playing animation', actions);

    actions['Armature|ReapTheWhirlwind'].fadeIn(0.5).warp(1, 0.6).play();
  }, [actions]);

  return (
    <group ref={ref} scale={0.06} position={[0, -20, 10]} rotation={[0, -2, 0]}>
      <primitive object={scene} {...props} />
    </group>
  );
});
Model.displayName = 'Model';

export default Model;
