name: Build

on:
  push:
    branches: ['development']
  pull_request:
    branches: ['development']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install
      - name: Linting
        run: yarn lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install
      - name: Test
        run: yarn test:cov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build --if-present
